name: deploy

on:
  push:
    branches: [dev] # dev 分支有 push 时触发

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: yarn install # 安装依赖

      - name: Test
        run: yarn test:unit # 打包

